Circleci 2.0 migration
Financial-Times/ec2-powercycle pull request #5
Opened 2018-05-03 13:26 UTC by JermilaPaulDhas

2018-05-03 13:38 UTC, jussi-ft approved these changes
Looks good to me!

2018-05-08 08:33 UTC, tamas-molnar commented
Deploy doesn't work, probably related to this: https://trello.com/c/px5t96WI/1010-cd-for-ec2powercycle-lambda-in-content-test-and-content-prod

2018-05-08 08:34 UTC, tamas-molnar requested changes
Fix CD?

2018-05-11 11:22 UTC, tamas-molnar approved these changes

2018-05-11 11:27 UTC, merged